spring:
  application:
    name: carbackend
  datasource:
    url: jdbc:mariadb://localhost:3306/cardb
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

#Windows
#uploadPath: C:/temp/images . . .


#Linux
#uploadPath: /home/temp